version: "3.5"

x-shared-config:
  base: &base
    stdin_open: true
    tmpfs:
      - /tmp
    user: "1069:1420"

  postgres_image_name: &postgres_image_name
    image: postgres:14.5-alpine

  rails_env_files: &rails_env_files
    env_file:
    - .env
    - .env.local

  rails_image_name: &rails_image_name
    image: mutations/rails:ruby3.1.2-alpine3.16-2022-10-11

  api: &api
    <<: *base
    depends_on:
      - postgres
    environment:
      - HISTFILE=/app/log/.bash_history
      - RAILS_ENV=${RAILS_ENV:-development}
    volumes:
      - .:/app:cached
      - app_cache:/app/tmp/cache
      - bundle:/bundle
    working_dir: /app

services:
  app:
    <<: *api
    <<: *rails_env_files
    <<: *rails_image_name
    command: bundle exec rails s -u puma -p 3000 -b 0.0.0.0
    depends_on:
      - caddy
      - postgres
    environment:
      RAILS_ENV: development

  caddy:
    image: caddy:2.6.1-alpine
    ports:
      - 443:443
    volumes:
      - ./.caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

  postgres:
    <<: *postgres_image_name
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  shell:
    <<: *api
    <<: *rails_image_name
    command: /bin/bash

volumes:
  app_cache:
  bundle:
  caddy_data:
  postgresql_data:
